name: GitHub Snake Game

on:
  # Schedule the workflow to run daily at midnight UTC
  schedule:
    - cron: "0 0 * * *"
  # Allow manual triggering of the workflow
  workflow_dispatch:
  # Trigger the workflow on pushes to the main branch
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Create dist directory
      - name: Create dist directory
        run: mkdir -p dist

      # Step 3: Generate the snake animations
      - name: Generate GitHub Contributions Snake Animations
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Verify files were generated
      - name: Verify generated files
        run: |
          if [ ! -f "dist/github-snake.svg" ]; then
            echo "Error: github-snake.svg was not generated"
            exit 1
          fi
          if [ ! -f "dist/github-snake-dark.svg" ]; then
            echo "Error: github-snake-dark.svg was not generated"
            exit 1
          fi
          if [ ! -f "dist/ocean.gif" ]; then
            echo "Error: ocean.gif was not generated"
            exit 1
          fi

      # Step 5: Debug token
      - name: Debug Token
        run: |
          echo "Checking GH_PAGES_TOKEN..."
          if [ -z "${{ secrets.GH_PAGES_TOKEN }}" ]; then
            echo "Error: GH_PAGES_TOKEN is not set"
            exit 1
          else
            echo "GH_PAGES_TOKEN is set"
          fi

      # Step 6: Deploy the generated files to the 'output' branch
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update snake animation [skip ci]"
          force_orphan: true